const mocks = {
    // Tasker built-ins
    SDK: "",

    // global
    DARK_MODE: "1",

    // local
    time_precision: "2",
    metrics_path: "benchmark.json",
    checkin_type: "Evening",
};

const mockFiles = {
    "benchmark.json": JSON.stringify([
        {
            "name": "readFile",
            "count": 100,
            "stats": {
                "min": 20.5,
                "first": 22.299999997019768,
                "avg": 31.538000000119208,
                "med": 30.099999997764826,
                "p95": 51.764999995753165,
                "p99": 56.25699999563399,
                "max": 61.900000005960464,
                "total": 3156.1999999955297,
            },
        },
        {
            "name": "readJsonFile",
            "count": 100,
            "stats": {
                "min": 25.600000001490116,
                "first": 40.30000000447035,
                "avg": 46.54400000020862,
                "med": 45.94999999925494,
                "p95": 67.80500000417233,
                "p99": 72.72000000149018,
                "max": 84.60000000149012,
                "total": 4655.60000000149,
            },
        },
    ]),

    "/sdcard/Tasker/json/checkin.json": JSON.stringify({
        "habits": [
            {
                "name": "cardio",
                "reminderText": "cardio workout",
                "lastDate": "2023-02-15",
                "daysSince": 1,
                "reminderThreshold": 2,
                "pastWeek": [
                    "2023-02-10",
                    "2023-02-12",
                    "2023-02-15",
                ],
                "tracked": true,
                "types": [
                    "hike",
                    "hiit",
                    "kayaking",
                    "ride",
                    "run",
                    "stair climber",
                    "stationary bike",
                ],
                "weeklyTarget": 3,
                "daysSinceWeeklyTargetLastMet": 1,
                "currentStreak": 1,
            },
            {
                "name": "journal",
                "reminderText": "journal entry",
                "lastDate": "2023-02-13",
                "pastWeek": [
                    "2023-02-09",
                    "2023-02-11",
                    "2023-02-12",
                    "2023-02-13",
                ],
                "tracked": true,
                "weeklyTarget": 3,
                "daysSince": 3,
                "daysSinceWeeklyTargetLastMet": 0,
                "currentStreak": 0,
            },
            {
                "name": "meditation",
                "reminderText": "meditation session",
                "lastDate": "2023-02-13",
                "reminderThreshold": 1,
                "pastWeek": [
                    "2023-02-09",
                    "2023-02-11",
                    "2023-02-12",
                    "2023-02-13",
                ],
                "tracked": true,
                "weeklyTarget": 3,
                "daysSince": 3,
            },
            {
                "name": "resistance",
                "reminderText": "resistance workout",
                "lastDate": "2023-02-14",
                "daysSince": 2,
                "reminderThreshold": 1,
                "pastWeek": [
                    "2023-02-09",
                    "2023-02-11",
                    "2023-02-13",
                    "2023-02-14",
                ],
                "tracked": true,
                "types": [
                    "calisthenics",
                    "lifting",
                ],
                "weeklyTarget": 3,
            },
            {
                "name": "sickInjured",
                "lastDate": "2023-02-15",
                "pastWeek": [
                    "2023-02-14",
                    "2023-02-15",
                ],
                "types": [
                    "sick",
                    "injured",
                ],
                "daysSince": 1,
            },
            {
                "name": "sleep",
                "lastDate": "2024-05-22",
                "daysSince": 1,
                "pastWeek": [
                    "2024-05-19",
                    "2024-05-21",
                    "2024-05-22",
                ],
                "weeklyTarget": 4,
            },
            {
                "name": "yoga",
                "avoid": true,
                "reminderText": "yoga/mobility work session",
                "lastDate": "2024-01-08",
                "daysSince": 2,
                "reminderThreshold": 1,
                "pastWeek": [
                    "2024-01-03",
                    "2024-01-04",
                    "2024-01-05",
                    "2024-01-06",
                    "2024-01-07",
                    "2024-01-08",
                    "2024-01-09",
                ],
                "types": [
                    "yoga",
                    "mobility work",
                ],
                "tracked": true,
                "weeklyTarget": 5,
            },
        ],
        "lists": {
            "evening": {
                "checkboxItems": {
                    "Habits": [
                        "Journal",
                        "Meditation",
                        "Morning sunlight",
                        "Read",
                    ],
                    "Exercise": [
                        "Calisthenics",
                        "Elliptical",
                        "HIIT",
                        "Hike",
                        "Kayaking",
                        "Lifting",
                        "Ride",
                        "Run",
                        "Stair climber",
                        "Stationary bike",
                        "Yoga",
                    ],
                    "Lifestyle": [
                        "Air travel",
                        "Alcohol**",
                        "Caffeine",
                        "Commuting",
                        "Late meal",
                        "Sauna",
                        "Work from home",
                    ],
                    "Status": [
                        "Injured",
                        "Seasonal allergies",
                        "Sick",
                    ],
                    "Meds & Supplements": [
                        "Aller-Clear",
                        "Aller-Flo",
                        "Apigenin",
                        "Creatine",
                        "Fish oil",
                        "Magnesium Glycinate",
                        "Theanine",
                        "Vitamin C",
                        "Vitamin D3",
                    ],
                },
                "rangeItems": {
                    "Mental Health": [
                        "Overall Mood",
                        "Irritability",
                        "Productivity",
                        "Sense of Control",
                        "Sense of Purpose",
                        "Stress",
                    ],
                },
            },
            "morning": {
                "checkboxItems": {
                    "Sleep": [
                        "Away from home",
                        "Fan",
                        "Heater",
                        "Humidifier",
                        "Open window",
                        "Screens <1hr before bed",
                        "Screens in bed",
                        "Shared bed",
                        "White noise",
                    ],
                },
                "rangeItems": {
                    "Sleep": [
                        "Feel Well-Rested",
                    ],
                },
            },
        },
        "rewards": {
            "habitsTarget": 4,
            "daysSinceLastRewardRoll": 3,
            "rollStreak": 0,
            "rewardList": [
                {
                    "name": "blank",
                    "weight": 50,
                    "timesAppeared": 0,
                },
                {
                    "name": "Backpacking",
                    "unredeemed": 0,
                    "weight": 8,
                    "timesAppeared": 1,
                },
                {
                    "name": "Restaurant",
                    "unredeemed": 3,
                    "weight": 8,
                    "timesAppeared": 0,
                },
                {
                    "name": "Weekend trip",
                    "unredeemed": 1,
                    "weight": 1,
                    "timesAppeared": 0,
                },
                {
                    "name": "Wishlist item",
                    "unredeemed": 2,
                    "weight": 8,
                    "timesAppeared": 1,
                },
            ],
        },
    }),

    "/sdcard/Tasker/json/expenses.json": JSON.stringify({
        "categories": [
            "Air travel",
            "Books",
            "Car insurance",
            "Car maintenance",
            "Car payment",
            "Cleaning",
            "Clothes",
            "Computer/Accessories",
            "Cycling",
            "Decor",
            "Electric bill",
            "Electronics",
            "Fitness",
            "Furniture",
            "Gas",
            "Gifts",
            "Groceries",
            "Haircut",
            "Hotels",
            "Internet",
            "Kitchen",
            "Medical",
            "Misc entertainment",
            "Outdoors",
            "Personal care",
            "Phone bill",
            "Rent",
            "Renter's insurance",
            "Restaurants",
            "Rideshare",
            "Running",
            "Software",
            "Subscriptions",
            "Supplements",
            "Taxes",
            "Tools",
            "Utilities",
            "Video games",
        ],
        "vendors": [
            "ALDI",
            "Amazon",
            "Costco",
            "Hilton",
            "IKEA",
            "Keychron",
            "Nintendo",
            "Southwest",
            "Spectrum",
            "Target",
            "Verizon",
            "Walgreens",
        ],
    }),
};
